### ISSUE TITLE
Microhydra0.10.bin it does not work.....for mi

### ISSUE THREAD

**Issue by leorrr** [bmorcelli/M5Stick-Launcher#13]
Help to run MicroHydra 0.10.bin downloaded from the folder compatibles binaries, I install the binary normaly like the others, it loads and when finished the screen is black...
any ideas?

**Comment by bmorcelli** [comment]
MicroHydra is only compatible with Cardputer, if you are trying in other device, it wont work.

And microhydra is only compatible with version 1.3 of Launcher.. that you can download [Here](https://github.com/bmorcelli/M5Stick-Launcher/releases/download/1.3.0/M5Launcher-1.3.0-M5Cardputer.bin)

Try reinstalling the last version of the llauncher with [Esp Home Io](http://web.esphome.io) and tell me if it works

**Comment by leorrr** [comment]
Hello, the version I had installed was 1.3 installed with "m5Burnet", I have reinstalled with the version you provided me through espHome as you advised and it **worked perfectly**, thank you very much.
