### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by vs4vijay** [bmorcelli/M5Stick-Launcher#17]
Where is the code? I don't see any *.ino or *.cpp files in the repo?

**Comment by bmorcelli** [comment]
Hey man... I'm a litle concearned about the M5 links and information... I will share the code in the near future

And I've changed the plataform too, now I'm working on PlatformIO and there are somethings I need to do to organize the code and share something manteinable

**Comment by bmorcelli** [comment]
Its here now, my friend!!
