### ISSUE TITLE
Unable to create folder in webUI

### ISSUE THREAD

**Issue by alecdvor** [bmorcelli/M5Stick-Launcher#18]
I am able to access the webUI via connection across my local wireless network. 
I am able to upload files but I receive the following error when attempting to create a folder. 
ERROR: file does not exist 
This occurs when I attempt to make a folder in the root folder 
I have an sd card in my cardputer and appears to be recognized and working correctly

**Comment by bmorcelli** [comment]
Hello,

I'll check this issue this week.. thank you for sharing this problem..

**Comment by bmorcelli** [comment]
https://github.com/bmorcelli/M5Stick-Launcher/issues/16 Look at this Issue, I fixed the Folder creation, and test the binary I sent there, please...

This file is pointing to a test repo, so OTA firmwares are outdated..
