### ISSUE TITLE
option to repartition or erase the internal storage

### ISSUE THREAD

**Issue by AssetBurned** [bmorcelli/M5Stick-Launcher#19]
Hi,

Not sure if that is the right wording. so please let me explain the problem.

I have multiple BIN files that i install via this launcher on the Cardputer. But at some point Microhydra won't install anymore and any attempt means I am getting stuck at the progress bar and a reboot will load the Launcher and i can nicely interact, but Microhydra won't load.
So i need to erase the Cardputer with M5burner and then refresh the launcher. Now i can use the Launcher to install Microhydra again and other images.

I can definitely reproduce this when I am switching between the Microhydra 1.0 image i got via M5burner and the CircuitPython 9.1.0-beta.1 BIN i got directly from https://circuitpython.org/board/m5stack_cardputer/ .

CU AssetBurned ;-)

**Comment by bmorcelli** [comment]
This problem occures because Circuit python overrites the boot.py file in the FAT partition, so when you  install microhydra again, MH won't remake the boot.py and it will not work as expected.. 

This same problem happens when using UIFlow.. I'll look for a way to format the FAT Partition and let it as an option in the Launcher, may be it'll deal with this problem..

**Comment by bmorcelli** [comment]
Hello @AssetBurned ..

I think I managed to format the FAT Partition, can you try it for me??
[Launcher_2_fix_Cardputer.zip](https://github.com/bmorcelli/M5Stick-Launcher/files/15284718/Launcher_2_fix_Cardputer.zip)

- Download the file
- Unzip it
- access: https://web.esphome.io 
- Install the bin file you just unzipped

It is pointing to a Test Repo, so the firmwares may be outdated.. it is only for test..

**Comment by AssetBurned** [comment]
Sorry, my cardputer and I are currently separated. I expect it back in my hands later this month. But happy to try as soon as I can.

**Comment by AssetBurned** [comment]
Follow up: Yes that seems to fix it :-D thank you!!!

Ah I see it is also part of the 2.0.1 release in the M5Burner. Great!
