### ISSUE TITLE
1 unico arquivo

### ISSUE THREAD

**Issue by JonasLacerda** [bmorcelli/M5Stick-Launcher#2]
tive que juntar os binarios pra poder postar o projeto... logo o codigo que eu usei pra para juntar os 3 arquivos do arduino em uma unica imagem: esptool.py --chip esp32s3 merge_bin --output projeto.bin 0x0000 projeto.ino.bootloader.bin 0x8000 projeto.ino.partitions.bin 0x10000 projeto.ino.bin

**Comment by bmorcelli** [comment]
Bom dia Jonas, tudo bem?

vc juntou os binários para colocar no cartão SD e iniciar pelo Launcher?

Os projetos binários exportados do Arduino IDE funcionam diretamente no Launcher, e é até melhor assim, pq diminui o tempo de processamento... é só copiar o "projeto.ino.bin", que é o binário da aplicação, pro cartão SD e partir pro abraço
