### ISSUE TITLE
How to unload firmware?

### ISSUE THREAD

**Issue by jaiwiwjwjwisn** [bmorcelli/M5Stick-Launcher#24]

**Comment by bmorcelli** [comment]
Flash other firmware in it's place, actually there are no option for user erase the app partition by himself..

**Comment by jaiwiwjwjwisn** [comment]
> Flash other firmware in it's place, actually there are no option for user erase the app partition by himself..

After loading a firmware how to use launcher? After boot auto loaded firmware runs.

**Comment by bmorcelli** [comment]
While in the Launcher's boot screen, Press Ok if using Cardputer, or M5 if using StickC

**Comment by jaiwiwjwjwisn** [comment]
Ok, thanks

**Comment by jaiwiwjwjwisn** [comment]
Ok, thanks.

**Comment by jaiwiwjwjwisn** [comment]
Solved
