### ISSUE TITLE
Update error 5 when installing Nemo 2.7.0

### ISSUE THREAD

**Issue by AssetBurned** [bmorcelli/M5Stick-Launcher#26]
Got the Memo 2.7.0 image from M5Burner and tried to install it with Launcher 2.0.1. But I get the "Update error 5". The 2.6.0 version (Shark 1.0.4 & Marauder 0.13.10) installs fine.

Images are stored on SD card in a subfolder.

**Comment by bmorcelli** [comment]
Hello, which device are you using? This version of Nemo is from the original author, N0x4?

**Comment by bmorcelli** [comment]
I tried here and couldn't reproduce the error..

try this binary: 
[Nemo 2.7 Cardputer.bin.zip](https://github.com/bmorcelli/M5Stick-Launcher/files/15461515/Nemo.2.7.Cardputer.bin.zip)
