### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by HACKERprise** [bmorcelli/M5Stick-Launcher#27]
M5 cplus
Bins on sd card
I put install, It supposedly installs but then it keeps restarting do not stop

**Comment by bmorcelli** [comment]
Hi, your StickC Plus is the 1.1 or 2?

The binaries for 1.1 doesn't work on 2... This can be a problem...

If you downloaded the binaries using the M5launcher OTA, there is a possibility of the files become corrupted in the process... So I suggest you download the binaries from the m5burner, as explained in the [Wiki](https://github.com/bmorcelli/M5Stick-Launcher/wiki/Obtaining-binaries-to-launch)

**Comment by HACKERprise** [comment]
1.1 I put it through m5burner
