### ISSUE TITLE
.zip extractor

### ISSUE THREAD

**Issue by Bulkoa** [bmorcelli/M5Stick-Launcher#28]
it would be awesome if you can upload a folder or multiple file at once to your device without any cable or SD-usb adapter.

**Comment by bmorcelli** [comment]
Hello!!

I just implemented multiple file upload into Bruce Firmware, with the help of a Discord friend.. it will be available there in the next update (today or tomorrow)

I will port this to Launcher in the next version, this is certain!

Ill keep the issue opened to keep track of the new asked features as I develop them

**Comment by Bulkoa** [comment]
thank you!

**Comment by bmorcelli** [comment]
I implemented multifile upload
