### ISSUE TITLE
UIFlow 2 is not compatible with M5Stick-Launcher

### ISSUE THREAD

**Issue by Unixware** [bmorcelli/M5Stick-Launcher#29]
Installing the UIFlow2 from its .bin file result in black screen, this does not happed when I burn it via M5Burner

**Comment by bmorcelli** [comment]
The Python core of UIFlow runs so you can connect to the computer and make some sketches, but the application that is saved in the vfs partition isn't installed yet..

I'm thinking in a way to make it work.. I will keep the issue opened to keep thinking about a solution.

**Comment by Unixware** [comment]
Thanks! Not an urgent  issue anyway.

**Comment by bmorcelli** [comment]
Now it will be compatible with custom partitioning.. 

https://github.com/bmorcelli/M5Stick-Launcher/wiki/Functionalities-explained

**Comment by Unixware** [comment]
Thanks ,just installed the new Launcher,  alas the fix does not seem to work for me, still black screen on UIFlow, 
could be incompatible Cardputer or SD card... who knows , nevermind.

**Comment by bmorcelli** [comment]
Hey man, yes indeed... I had it working, and idk what I've done that broke it again..

Sorry

I'll keep working on that

https://github.com/bmorcelli/M5Stick-Launcher/assets/104320209/a4efc7fb-1b8f-4eb1-bb71-633ba9bd05ba

**Comment by Unixware** [comment]
Its ok I really appreciate your effort, no need to proof that worked, but that video is quite helpful, as in my case I don't see the 'Installing SPIFFS' , instead goes to "Updatining FAT" maybe is some step I ve missed...

**Comment by bmorcelli** [comment]
No, you have not.. It was in the testing, and I haven't changed some names yet..

You did fine, its the partition copying that isn't working anymore =(
