### ISSUE TITLE
Using Launcher.ino, boot bin, then can't go back

### ISSUE THREAD

**Issue by reggi** [bmorcelli/M5Stick-Launcher#3]
After I boot into a selected .bin file, I can't go back to the launcher. Is there a way? I'm using a cardputer and tried pressing `BtnA` || Enter.

**Comment by bmorcelli** [comment]
Hi reggi, have you installed the launcher from m5burner or tried to build it from source?

I recommend install from m5burner or download the .bin file from last release page and flash it with web.esphome.io

When flashed properly, it boots every time you turn on the Cardputer, reboot command from app doesn't work... That way it must show a white screen asking to press Enter (G0 also works)



To build it from source you must use my custom bootloader_CP.bin, from support_files, following the instructions from readme... If you don't use it, you won't be able to get back to the launcher.
