### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by h3nd0123** [bmorcelli/M5Stick-Launcher#34]
when I enter Wi-Fi details it takes me its supposed to show me all the firmwares available but they aren't popping up but you can still flick through just not knowing what you're clicking.

**Comment by bmorcelli** [comment]
Hello, what device are you using?
It happens when you enter in the OTA, right?

As I've used Sprites to draw the screens, the memory available to the json file becomes a bit short...

I'm now working on the "deSpeitezation" of all screens, to leave more memory to the main process
