### ISSUE TITLE
Spiffs window scrambled

### ISSUE THREAD

**Issue by loewal** [bmorcelli/M5Stick-Launcher#37]
Hi,
I noticed the following changes on my cardputer:
- the loading of SPIFFS is only then readable when moving the cursor up or down -- bug?
- the Matrix-simulation is i.m.h.o. not as nice as in v.2.0.1...
- loading Saturn from OTA gives a Portugese version (or SPanish?) -- not your fault I presume

Can it be repaired?

Grtz.

**Comment by loewal** [comment]
> Hi, I noticed the following changes on my cardputer:
> 
> * the loading of SPIFFS is only then readable when moving the cursor up or down -- bug?
> * the Matrix-simulation is i.m.h.o. not as nice as in v.2.0.1...
> * loading Saturn from OTA gives a Portugese version (or SPanish?) -- not your fault I presume
> 
> Can it be repaired?
> 
> Grtz.

Sorry, third is solved. My fault.

**Comment by bmorcelli** [comment]
Hello,

> * the loading of SPIFFS is only then readable when moving the cursor up or down -- bug?

I changed the way the screen is drawn, so something became out of place, somehow.. but i just fixed it.. will be released in minutes

> * the Matrix-simulation is i.m.h.o. not as nice as in v.2.0.1...

I apreciate it.. but the other matrix used "sprites" to work, and it is not viable without it... I left sprites behind to leave more RAM available for other parts of the code.
