### ISSUE TITLE
Web listing (m5lurner) shows the oldest version of a firmware first

### ISSUE THREAD

**Issue by andypiper** [bmorcelli/M5Stick-Launcher#38]
I find it a bit counter-intuitive that on https://bmorcelli.github.io/M5Stick-Launcher/m5lurner.html the *least* recent version of each firmware is the default selected in the drop-down box - it would probably be better to swap that so that the *most* recent is default, but a user can choose to get an older version if they need to.

**Comment by bmorcelli** [comment]
Yes, you are right.. 

I'm not an expert on Json and Html/JavaScript, but I'll try to fix it this evening and release the 2.1 bugfixes tonight

**Comment by bmorcelli** [comment]
I just changed the JSON source code, from [Here](https://github.com/bmorcelli/M5Stack-json-fw/blob/main/script/update_json.py) and now it is ordering for "published_at" putting the most recent on top in the list..

Feel free to submit enhancements on the code
