### ISSUE TITLE
Black screen on CoreS3

### ISSUE THREAD

**Issue by loewal** [bmorcelli/M5Stick-Launcher#45]
Hi,
After flashing the Launcher on my CoreS3 the screen stays black.
Tried a different app and that works well.
Perhaps only for CoreS3SE?
Regards

**Comment by bmorcelli** [comment]
No, indeed it might not be working at all...  I'll suspend this firmware for now, until I find a Solution

**Comment by bmorcelli** [comment]
![IMG_20240809_210721477.jpg](https://github.com/user-attachments/assets/e30299e3-33f9-4cda-8aa5-54ed2d202381)
