### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by bmorcelli** [bmorcelli/M5Stick-Launcher#46]
* When Downloading firmware, sometimes the connection drops and doesn report any error message
     * [x] Add other condition to monitor the connection or time between packets
     * [x] At the end Check the downloaded file size compared to what should be, and delete it if it is smaller

* Fail to open the WebUI at the first time when not using an SD Card (T-Display)

* Ad exFAT support to M5Launcher (move to [SdFat](https://github.com/greiman/SdFat/) lib with SD_FAT_TYPE = 3)

**Comment by mio-19** [comment]
How is exfat support?

**Comment by bmorcelli** [comment]
Was not implemented yet
