### ISSUE TITLE
No Apps loaded on the old StickCPlus

### ISSUE THREAD

**Issue by cortmen** [bmorcelli/M5Stick-Launcher#5]
Version 1.1.3 download from release
On my **M5Stack StickCPlus**     -> Message "no Apps loaded!  
M5Launcher-1.1.3-M5StickCPlus.bin 

on my **M5Stack StickCplus2**  - > all ready loaded files
M5Launcher-1.1.3-M5StickCPlus2.bin

I use the same SD Card Adapter and SD Card 
Any solution for the M5Stack StickCPlus?

**Comment by cortmen** [comment]
I swapped the SD card once, if I confirm the "ok" button very quickly directly after flashing,
I can load a program once. After that there is no boot menu / start menu, the last app is loaded directly.
The M5Stack StickCplus2 does not make such "bitches"

**Comment by bmorcelli** [comment]
Hey friend, let me see if I understood.

- You flashed M5Launcher-1.1.3-M5StickCPlus.bin, downloaded from this repo, on a StickC Plus
- when you turn it on, after flash, it shows the Launcher screen to press M5 and enter the app
- so you choose a binary and after flashing an app using the Launcher, you are not able to open Launcher again

Is this?

Note: the launcher app will only appear when you turn on the device... Restart commands from apps won't work.. you must turn it off and on again for the Bootloader does it's trick

If you are plugged on USB, you must disconnect usb, turn off and on again.

**Comment by cortmen** [comment]
Thank you for your support. Yes, you understood correctly.
A little more information.

Stick off, correctly off, USB is not connected.
I know this behavior from the Plus2 which is here.

When I reflash, I have to press the M5 button extremely quickly to get the start menu at all. 
If I don't press M5, the message "No apps" appears immediately and it stays with this message until I reflash.
Then I get the start menu again once (if I press M5 quickly) and can then install an app exactly once. This app is then started immediately and permanently, the selection menu is gone.

esptool.exe -p COM5 -b 115200 --before default_reset --after hard_reset --chip esp32 write_flash --flash_mode dio --flash_freq 40m --flash_size detect 0x0 M5Launcher-1.1.3-M5StickCPlus.bin


The M5StackCPlus2 runs perfectly. Could this be something with the partitions?

**Comment by bmorcelli** [comment]
No, it seams to be something with bootloader

As I don't have a stick plus to do the testing, can you add me on Discord, so we can  figure out a solution for this?

user: bmorcelli or Pirata#5263

**Comment by cortmen** [comment]
thx for your help, i have the M5StackCPlus2 and this is ok.

**Comment by cortmen** [comment]
A small addendum, the boot menu on the StickCPlus can be reactivated, including the additional *.bin selection, if an 
esptool.exe -p COM16 -b 115200 --before default_reset or --after hard_reset is sent. 

This process must be carried out each time an app is changed.

Unfortunately this was not possible with all versions including Cardputer:
load the appropriate UiFlow_v2.02.bin files.  Result Loader hangs.

All matching UiFlow_v2.02.bin for cardcuter, StickCPlus and CStickPlus2, the loader does not like this kind of official bins.
