### ISSUE TITLE
Display stuck at various points??

### ISSUE THREAD

**Issue by raichea** [bmorcelli/M5Stick-Launcher#66]
I've just got a Cardputer and have installed M5 Launcher (v2.2.4) on it, which is working well. 

After downloaded a binary to the SD card the screen appears to be stuck at "Downloaded". I randomly press buttons (ESC, Enter etc) hoping to clear it, but nothing does - eventually the display does return to normal operation. 

I see similar behaviour after listing partitions... the list hangs around but can't be cleared although it does eventually go away.

is this intentional? If so, the delay does seem a bit long - I'd personally prefer that a suitable keypress cleared the displayed info.

**Comment by bmorcelli** [comment]
> After downloaded a binary to the SD card the screen appears to be stuck at "Downloaded". I randomly press buttons (ESC, Enter etc) hoping to clear it, but nothing does - eventually the display does return to normal operation.

It is wainting for you to press "Ok" to go away 
 
> I see similar behaviour after listing paritioins... the list hangs around but can't be cleared although it does eventually go away.
> 
> is this intentional? If so, the delay does seem a bit long - I'd personally prefer that a suitable keypress cleared the displayed info.

It is waiting you press "Ok" to confirm the action, and go away

**Comment by raichea** [comment]
It doesn't seem that I can reopen this but when I said I pressed 'Enter' as one of the keys I tried,has been flipped during the upload. I tried uploading a few times but this one gets flipped every time, but I hope you'll see what I mean)

https://github.com/user-attachments/assets/991e2018-a878-4c6b-bbfc-a9b635b08d3c
 I should have said 'OK'. Pressing it doesn't remove the message.

Here's a video. The video for the other issue uploaded OK but, for some reason, this one gets flipped during the upload. I tried uploading a few times but this one gets flipped every time, but I hope you'll see what I mean)

https://github.com/user-attachments/assets/991e2018-a878-4c6b-bbfc-a9b635b08d3c

**Comment by bmorcelli** [comment]
it is waiting for 2s after press the btn https://github.com/bmorcelli/M5Stick-Launcher/blob/0ba9a86b23edb1822c293c4295d23d6bf7f2f54c/src/onlineLauncher.cpp#L276

I will remove it from the code as well, because it is now waitinh user´s input

**Comment by raichea** [comment]
Ah, that explains it. Thanks.
