### ISSUE TITLE
Splash screen not readable

### ISSUE THREAD

**Issue by raichea** [bmorcelli/M5Stick-Launcher#67]
Just an aesthetic thing, but when I first installed M5 Launcher (v2.2.4), the splash screen showed the name before being obliterated by random characters. After using M5 Launcher to install some firmware, the splash screen is no longer readable - it's as though the first couple of seconds of the animation are being skipped.

**Comment by bmorcelli** [comment]
Can you send me a video, please?

**Comment by raichea** [comment]
No problem - here it is. I've also added a video to show the problem for the [issue you closed](https://github.com/bmorcelli/M5Stick-Launcher/issues/66):

https://github.com/user-attachments/assets/86df7d9a-c514-4c36-9458-f74cacde11ac

**Comment by bmorcelli** [comment]
Ok, I will make the Launcher text with a different color (darker) in this green scheme..

**Comment by raichea** [comment]
Thanks, that will improve things, but I'm wondering why the first part of the animation goes missing
