### ISSUE TITLE
ajuda

### ISSUE THREAD

**Issue by 9111Jonatassouza** [bmorcelli/M5Stick-Launcher#70]
Can you please put a language menu if it is possible in Portuguese br?

**Comment by bmorcelli** [comment]
Particularmente eu não vejo motivo para isso.. são poucas coisas para ler e escolher no programa.. e traduzir vai aumentar o numero de versões de 8 para 16 (12 deles para postar no m5burner, o que é bem chato de fazer).. muito trabalho para um ganho de conforto insignificante..

Por isso que o Launcher não será traduzido (pelo menos não por mim)

Mas vc tem a opção de criar um fork do projeto, traduzir e usar 😉

**Comment by r0bertgabriel** [comment]
realmente é um trabalho que tem pouco ganho
