### ISSUE TITLE
Mounting the SD Card from UIFlow 2 or Micropython

### ISSUE THREAD

**Issue by scarolan** [bmorcelli/M5Stick-Launcher#72]
Is this even possible?  When I tried to mount the SD card the normal way when booted into the UIFlow image, I only see a file called RRaA and it's not readable or writeable....

**Comment by bmorcelli** [comment]
I'm not familiar with Uiflow and microhydra programs to debug it, but if Launcher is reading the files right, probably they are not recognizing the SDCard properly or idk.. because they both run over micropython
