### ISSUE TITLE
T-DISPLAY S3 PRO ERROR

### ISSUE THREAD

**Issue by fermintm** [bmorcelli/M5Stick-Launcher#73]
Is not compatible with T-Display s3 Pro???

**Comment by bmorcelli** [comment]
Unfortunately no :(

Not yet

**Comment by fermintm** [comment]
I look forward to the launcher for this model :)

**Comment by bmorcelli** [comment]
Lilygo sent me this device last week.. probably I'll have it in hands in a few weeks 😜

**Comment by fermintm** [comment]
Oh Yeaaah!

**Comment by bmorcelli** [comment]
REleased version 2.4.1 with port to this device!

**Comment by fermintm** [comment]
OMG!!!!!!!
About an hour ago I checked to see if there was an update and there wasn't one. Now is there one? I'll install it tomorrow, I don't have a computer at hand right now.

Thanksssss!!!!!!
