### ISSUE TITLE
Cardputer: Always says "Insert SD Card"

### ISSUE THREAD

**Issue by Meniny** [bmorcelli/M5Stick-Launcher#8]
I'm sorry if this is a dumb question. I am new to this.

so I have a 32GB SanDisk card with GPT table and a NTFS partition. I put some `.bin` files (nemo) into that partition. but the Launcher always says "Insert SD Card Hat or Insert SD Card or not formatted in FAT32".

I don't get it. What should I do now? Thanks.

**Comment by bmorcelli** [comment]
Format your SD card in FAT32..

It will clear the sdcard, so make a backup of your data.

It is not a limitation of the Launcher itself, but of ESP32 devices and libraries that don't recognize NTFS and other kinds of partitions.
