### ISSUE TITLE
CYD support (2.4+Capactive)

### ISSUE THREAD

**Issue by Teapot174** [bmorcelli/M5Stick-Launcher#80]
I would like you to add support for the new CYD.
I have this CYD and I can't figure out what it is.
It has a 2.4screen as well as a Capactive touch, ESP32-2432S024 is written on the back, this CYD has a Type-C port. It has pins (GND, O35, O22, O21) x2 as well as Bat+ Bat- and one I2C. The packaging said ESP32-2432S024C

**Comment by bmorcelli** [comment]
Hello...

Can you please try the beta version?

[Web Flasher](https://bmorcelli.github.io/M5Stick-Launcher/)
![image](https://github.com/user-attachments/assets/7176767f-5d9a-442e-b37f-bfdb1aabcea6)

**Comment by Teapot174** [comment]
Yes, it works

**Comment by bmorcelli** [comment]
Great!! Thank you!

**Comment by Blacktrecks** [comment]
I would like you to add support for the new CYD.
I have this CYD and I can't figure out what it is.
It has a 2.4screen as well as a Resistive touch, ESP32-2432S024 is written on the back, this CYD has a Type-C port. It has pins (GND, O35, O22, O21) x2 as well as Bat+ Bat- and one I2C. The packaging said ESP32-2432S024C. I have tried all the versions and release it only sbow me the interface for the capacitive variant... I dont know what to do
