### ISSUE TITLE
CYD orientation error

### ISSUE THREAD

**Issue by Teapot174** [bmorcelli/M5Stick-Launcher#84]
When flipping the orientation from the standard one, the buttons on the menu do not work when restarting, and when restarting again, the orientation returns to the standard one

**Comment by bmorcelli** [comment]
Hey friend, I think this rotation issue was fixed in the Beta too.. if you could test it please..

A known issue fot CYD is that brightness control os broken again (as it is in bruce 😢)

**Comment by bmorcelli** [comment]
This issue happens when SD Card is plugged, it is not saving/retrieving information correctly from there

**Comment by bmorcelli** [comment]
Fixed in here https://github.com/bmorcelli/M5Stick-Launcher/commit/82e7e6f31f4523664803d371cef6a693f747dc08
