### ISSUE TITLE
partition error

### ISSUE THREAD

**Issue by HyperBeats** [bmorcelli/M5Stick-Launcher#88]
Hello 

I get this error when I try to launch a firmware from the sd card

![image](https://github.com/user-attachments/assets/7dfc56b6-1f8a-4fe0-b6d0-54e7136325bc)

**Comment by HyperBeats** [comment]
i use this https://bmorcelli.github.io/M5Stick-Launcher/ to flash my cyd

**Comment by bmorcelli** [comment]
What firmware are you trying to install?

If you are installing Bruce, you must use the Lite version.. the binaries start with: Bruce-LAUNCHER-.....bin

**Comment by HyperBeats** [comment]
hooo okay its work now thanks you
