### ISSUE TITLE
Feature Request: Support Hidden Networks

### ISSUE THREAD

**Issue by tomcarlson** [bmorcelli/M5Stick-Launcher#89]
I use hidden networks and frequently have to return devices I purchase on Amazon because they can't imagine connecting to something that doesn't appear on a Wi-Fi scan.   So not supporting hidden networks certainly has precedent.

However the antennas in many of these M5Stack devices are not great.  Their Wi-Fi scans miss a ton of nearby networks, so perhaps it would still be helpful, even for normals, to be able to type in an SSID to connect to.

**Comment by bmorcelli** [comment]
Added this possibility into the Beta Release.. you can install using the web flasher

https://bmorcelli.github.io/M5Stick-Launcher/

Can you test it for me? It will scan the networks and the last option (above return to menu) will be "Hidden SSID", where you can type the network SSID and then the Passworkd
