### ISSUE TITLE
M5 cardputer launch UIFlow2 reboots in a loop (Was Issue #77)

### ISSUE THREAD

**Issue by wooodz** [bmorcelli/M5Stick-Launcher#92]
Hi,

I am having the same problem as reported in issue #77 Using version UIFlow2.0 (v2.2)

and Launcher v2.4.1 where Launcher keeps rebooting trying to load UIFlow.

**Comment by wooodz** [comment]
Also to add if I try to install UIFlow2.0 (2.1.8 or 2.1.9) I just get a blank screen after Launcher loads. I have set the CFG to UIFLOW2 and when I list the part I get OTA-FAT-FAT.

**Comment by bmorcelli** [comment]
Are you installing through OTA or with the binary in your SD Card?

**Comment by wooodz** [comment]
I’m installing using the SD card.

**Comment by wooodz** [comment]
Hi 

Also just tried OTA update it installed FW and connected and updated FAT twice. On restarting it just reboots over and over again.

**Comment by bmorcelli** [comment]
UIFlow is getting bigger and bigger.. I think I fixed it in the Beta Release, that you can install using the web flasher

https://bmorcelli.github.io/M5Stick-Launcher/

**Comment by wooodz** [comment]
Thanks all working now.
